### ISSUE TITLE
MeiliPHP version

### ISSUE THREAD

**Issue by ryanmitchell** [lunarphp/meilisearch#1]
Is there a reason why you're targeting 0.21.0 instead of the latest version of meiliphp (0.25.0)?
Its caused a composer downgrade on our side which has a knock on effect to other packages.

**Comment by AlexDanault** [comment]
I too am blocked by this outdated requirement, can it be bumped please ?

**Comment by AphgaDesign** [comment]
I'm blocked too!

**Comment by AlexDanault** [comment]
In the meantime, if you are stuck you can use this, it seems to work:

`composer require -W "meilisearch/meilisearch-php":"0.26.1 as 0.21.0"`
